checkpoints:
  checkpoint_interval: 250
  checkpoints_path: checkpoints/HyperLlama-180M-estonian-1x
  checkpoints_path_is_shared_file_system: false
  load_lr_scheduler: false
  load_optimizer: false
  resume_checkpoint_path: checkpoints/HyperLlama-180M-english-1x/3572
  resume_metadata: false
  save_final_state: true
  save_initial_state: false
data_stages:
- data:
    dataset:
      dataset_folder:
      - processed_datasets/estonian_nanoset_train_shuffled
      - processed_datasets/random_sample_initial_model_data_estonian_nanoset
      - processed_datasets/random_sample_code_estonian_nanoset
      dataset_max_tokens: null
      dataset_num_samples:
      - 8005170
      - 124361
      - 14094
      dataset_weights:
      - 8005170.0
      - 124361.0
      - 14094.0
      drop_last: false
      pad_samples_to_global_batch_size: true
      return_positions: true
      shuffle_files: true
      skip_in_stream: false
      token_size_in_bytes: 4
      tokenizer_name: meta-llama/Llama-3.3-70B-Instruct
      use_old_brrr_dataloader: false
      vocab_size: 128256
    num_loading_workers: 0
    seed: 42
  name: first epoch
  start_training_step: 1
- data:
    dataset:
      dataset_folder:
      - processed_datasets/estonian_nanoset_train_shuffled
      - processed_datasets/random_sample_initial_model_data_estonian_nanoset
      - processed_datasets/random_sample_code_estonian_nanoset
      dataset_max_tokens: null
      dataset_num_samples:
      - 8005170
      - 124361
      - 14094
      dataset_weights:
      - 8005170.0
      - 124361.0
      - 14094.0
      drop_last: false
      pad_samples_to_global_batch_size: true
      return_positions: true
      shuffle_files: true
      skip_in_stream: false
      token_size_in_bytes: 4
      tokenizer_name: meta-llama/Llama-3.3-70B-Instruct
      use_old_brrr_dataloader: false
      vocab_size: 128256
    num_loading_workers: 0
    seed: 137
  name: second epoch
  start_training_step: 1592
- data:
    dataset:
      dataset_folder:
      - processed_datasets/estonian_nanoset_train_shuffled
      - processed_datasets/random_sample_initial_model_data_estonian_nanoset
      - processed_datasets/random_sample_code_estonian_nanoset
      dataset_max_tokens: null
      dataset_num_samples:
      - 8005170
      - 124361
      - 14094
      dataset_weights:
      - 8005170.0
      - 124361.0
      - 14094.0
      drop_last: false
      pad_samples_to_global_batch_size: true
      return_positions: true
      shuffle_files: true
      skip_in_stream: false
      token_size_in_bytes: 4
      tokenizer_name: meta-llama/Llama-3.3-70B-Instruct
      use_old_brrr_dataloader: false
      vocab_size: 128256
    num_loading_workers: 0
    seed: 59
  name: third epoch
  start_training_step: 3183
- data:
    dataset:
      dataset_folder:
      - processed_datasets/estonian_nanoset_train_shuffled
      - processed_datasets/random_sample_initial_model_data_estonian_nanoset
      - processed_datasets/random_sample_code_estonian_nanoset
      dataset_max_tokens: null
      dataset_num_samples:
      - 8005170
      - 124361
      - 14094
      dataset_weights:
      - 8005170.0
      - 124361.0
      - 14094.0
      drop_last: false
      pad_samples_to_global_batch_size: true
      return_positions: true
      shuffle_files: true
      skip_in_stream: false
      token_size_in_bytes: 4
      tokenizer_name: meta-llama/Llama-3.3-70B-Instruct
      use_old_brrr_dataloader: false
      vocab_size: 128256
    num_loading_workers: 0
    seed: 888
  name: fourth epoch
  start_training_step: 4774
- data:
    dataset:
      dataset_folder:
      - processed_datasets/estonian_nanosets_train_shuffled_partial
      - processed_datasets/random_sample_initial_model_data_estonian_nanoset_partial
      - processed_datasets/random_sample_code_estonian_nanoset_partial
      dataset_max_tokens: null
      dataset_num_samples:
      - 3635611
      - 56667
      - 6499
      dataset_weights:
      - 3635611.0
      - 56667.0
      - 6499.0
      drop_last: false
      pad_samples_to_global_batch_size: true
      return_positions: true
      shuffle_files: true
      skip_in_stream: false
      token_size_in_bytes: 4
      tokenizer_name: meta-llama/Llama-3.3-70B-Instruct
      use_old_brrr_dataloader: false
      vocab_size: 128256
    num_loading_workers: 0
    seed: 10
  name: fifth epoch
  start_training_step: 6365
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: edulm_v2
  run: HyperLlama-180M-estonian-1x
  seed: 42
  step: null
logging:
  iteration_step_info_interval: 5
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.041666666666666664
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 0
    eos_token_id: 0
    hidden_act: gelu
    hidden_size: 576
    initializer_range: 0.041666666666666664
    intermediate_size: 1536
    is_llama_config: true
    max_position_embeddings: 2048
    num_attention_heads: 9
    num_hidden_layers: 30
    num_key_value_heads: 3
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_interleaved: false
    rope_scaling: null
    rope_theta: 10000.0
    tie_word_embeddings: true
    use_cache: true
    vocab_size: 128256
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.003
    lr_decay_starting_step: 5667
    lr_decay_steps: 1420
    lr_decay_style: linear
    lr_warmup_steps: 15
    lr_warmup_style: linear
    min_decay_lr: 0
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.01
  zero_stage: 0
parallelism:
  dp: 16
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  recompute_layer: false
  tp: 1
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
  tp_recompute_allgather: true
profiler: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: meta-llama/Llama-3.3-70B-Instruct
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 40
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 8
  sequence_length: 2048
  train_steps: 7087
  val_check_interval: 250
